#!/usr/bin/python -tt

"""
POST-COMMIT HOOK

 The post-commit hook is invoked after a commit.  Subversion runs
 this hook with the following ordered arguments:

   [1] REPOS-PATH   (the path to this repository)
   [2] REV          (the number of the revision just committed)
 Because the commit has already completed and cannot be undone,
 the exit code of the hook program is ignored.
"""

import sys

from optparse import OptionParser

from vcsamqp.settings import AMQP
from vcsamqp.hooks.svn import SvnHooks

from vcsamqp.senders.log import FileLogger
from vcsamqp.senders.amqp import BlockingAMQPSender, AsyncAMQPSender

def parse_args(argv):
    """ Commandline parser """
    parser = OptionParser(usage="%prog [options]")
    parser.add_option("--type", dest="type", metavar="<type of sender>",
                      default="amqp-async",
                      help="amqp-blocking, amqp-async and log are supported")

    return parser.parse_args(argv)


def main(argv):
    """Script entry point."""

    options, args = parse_args(argv)

    if options.type == "amqp-async":
        sender = AsyncAMQPSender(AMQP)
    elif options.type == "amqp-blocking":
        sender = BlockingAMQPSender(AMQP)
    elif options.type == "log":
        sender = FileLogger("/tmp/postcommit.log")

    SvnHooks(sender).postcommit(args[1], args[2])
    return 0

if __name__ == '__main__':
    sys.exit(main(sys.argv))
